version: '2'

services:
  django:
    build: ./django
    volumes:
      - ./django:/webapp
    depends_on:
      - node
      - celery

  celery:
    build: ./django
    command: celery worker -A celery_realtime -l info
    volumes:
      - ./django:/webapp
    depends_on:
      - redis

  node:
    build: ./node
    volumes:
      - ./node:/nodeapp
    depends_on:
      - redis
    ports:
      - "3000:3000"

  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - django

  redis:
    image: redis
